"""add tariffs

Revision ID: 2a85291edec6
Revises: 2444afb4e493
Create Date: 2026-09-23 08:19:34.175060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a85291edec6'
down_revision: Union[str, None] = '2444afb4e493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('package', 'open', name='tariffkind', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('hourly_rate', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(kind = 'package' AND duration_min IS NOT NULL AND price IS NOT NULL AND hourly_rate IS NULL) OR (kind = 'open' AND duration_min IS NULL AND price IS NULL AND hourly_rate IS NOT NULL)", name='ck_tariffs_kind_fields'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariffs')
    # ### end Alembic commands ###
