"""add business_day last_reminder_at

Revision ID: 5fd397c9b277
Revises: dce1736f9de9
Create Date: 2026-09-25 06:52:16.649061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd397c9b277'
down_revision: Union[str, None] = 'dce1736f9de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_days', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_days', 'last_reminder_at')
    # ### end Alembic commands ###
