"""add session_segments created_at

Revision ID: 6dc43ed7a066
Revises: 5fd397c9b277
Create Date: 2026-09-30 23:43:22.877592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc43ed7a066'
down_revision: Union[str, None] = '5fd397c9b277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_segments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_segments', 'created_at')
    # ### end Alembic commands ###
