"""add sessions and session segments

Revision ID: c77e389ac558
Revises: eb1e5711d6d8
Create Date: 2026-09-23 08:25:16.623899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77e389ac558'
down_revision: Union[str, None] = 'eb1e5711d6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('console_id', sa.Integer(), nullable=True),
    sa.Column('business_day_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('paid', 'free', 'service', name='sessionkind', native_enum=False, length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'finished', 'cancelled', name='sessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_day_id'], ['business_days.id'], ),
    sa.ForeignKeyConstraint(['console_id'], ['consoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('package', 'open', name='segmentkind', native_enum=False, length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_snapshot', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_segments')
    op.drop_table('sessions')
    # ### end Alembic commands ###
